version: "3.5"
services:
  frontend:
    build: ./
    encrypted_env_file: .env.encrypted
  cdn-prod-deployer:
    build: ./
    dockerfile: ./Dockerfile.build.prod
    encrypted_env_file: .env.encrypted
    args:
      # Replace with your Deploy URL
      deploy_url: https://www.rubricaURP.com/
    volumes:
      - ./docker:/docker
